import MediaWikiContent from "../../../../../MediaWikiContent";
import { MediaWikiBreak } from "../../../../MediaWikiBreak";
import { MediaWikiDate } from "../../../../MediaWikiDate";
import { MediaWikiFile } from "../../../../MediaWikiFile";
import { MediaWikiLink } from "../../../../MediaWikiLink";
import { InfoboxNo } from "../InfoboxTemplate.types";

export type InfoboxItem = {
  name: string;
  image: MediaWikiFile | (MediaWikiFile | MediaWikiBreak)[];
  release: MediaWikiDate | "";
  update: string;
  removal?: MediaWikiDate;
  removalupdate?: MediaWikiLink;
  aka?: string;
  members: boolean;
  quest: MediaWikiLink | InfoboxNo;
  tradeable: boolean;
  bankable?: boolean;
  stacksinbank?: boolean;
  placeholder?: boolean;
  equipable: boolean;
  stackable: boolean;
  noteable?: boolean;
  edible?: boolean;
  options: string[];
  wornoptions?: string[];
  destroy?: string;
  examine: string;
  value: number;
  alchable?: boolean;
  weight: string;
  respawn?: number;
  exchange?: boolean;
  gemwname?: string;
  id: string;
  trailblazerRegion?: string;
};
