name: Push Main

on:
  push:
    branches:
      - main

jobs:
  lint_build_test:
    name: "Lint, Built, & Test"
    uses: ./.github/workflows/action-lint-build-test.yml
    secrets: inherit

  changeset:
    name: "Changeset"
    needs: lint_build_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          cache: yarn
          node-version: 18

      - name: Install yarn packages
        run: yarn install --frozen-lockfile

      - name: Create Release Pull Request or Release
        id: changeset
        uses: changesets/action@v1
        with:
          publish: yarn release
          title: Version Release
          commit: Version Release
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_PACKAGES }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
